#define KEY_KB_A 30   // Key A
#define KEY_KB_B 48   // Key B
#define KEY_KB_C 46   // Key C
#define KEY_KB_D 32   // Key D
#define KEY_KB_E 18   // Key E
#define KEY_KB_F 33   // Key F
#define KEY_KB_G 34   // Key G
#define KEY_KB_H 35   // Key H
#define KEY_KB_I 23   // Key I
#define KEY_KB_J 36   // Key J
#define KEY_KB_K 37   // Key K
#define KEY_KB_L 38   // Key L
#define KEY_KB_M 50   // Key M
#define KEY_KB_N 49   // Key N
#define KEY_KB_O 24   // Key O
#define KEY_KB_P 25   // Key P
#define KEY_KB_Q 16   // Key Q
#define KEY_KB_R 19   // Key R
#define KEY_KB_S 31   // Key S
#define KEY_KB_T 20   // Key T
#define KEY_KB_U 22   // Key U
#define KEY_KB_V 47   // Key V
#define KEY_KB_W 17   // Key W
#define KEY_KB_X 45   // Key X
#define KEY_KB_Y 21   // Key Y
#define KEY_KB_Z 44   // Key Z

#define KEY_KB_0 11   // Key 0
#define KEY_KB_1 2    // Key 1
#define KEY_KB_2 3    // Key 2
#define KEY_KB_3 4    // Key 3
#define KEY_KB_4 5    // Key 4
#define KEY_KB_5 6    // Key 5
#define KEY_KB_6 7    // Key 6
#define KEY_KB_7 8    // Key 7
#define KEY_KB_8 9    // Key 8
#define KEY_KB_9 10   // Key 9
